import { Deal } from './deal.entity';

/** 초기 시드 데이터 */
export const seedDeals: Partial<Deal>[] = [
  // === 공동구매 ===
  {
    type: 'group-buy',
    title: '코스트코 휴지 30롤 같이 사실 분',
    description:
      '코스트코 화장지 30롤이 너무 많아서 나눠 사려고 해요. 10롤씩 3명이서 나눠요! 개당 가격이 훨씬 저렴합니다.',
    imageUrl: 'https://picsum.photos/seed/tissue01/400/300',
    originalPrice: 28900,
    groupPrice: 9700,
    currentParticipants: 2,
    targetParticipants: 3,
    deadline: '2026-06-12',
    organizer: '김민수 (전산학부 22)',
    category: '생활용품',
    status: 'active',
  },
  {
    type: 'group-buy',
    title: '쿠팡 생수 2L 24병 공구',
    description:
      '기숙사에서 생수 대량으로 사면 병당 400원대! 12병씩 나눠가질 분 모집합니다.',
    imageUrl: 'https://picsum.photos/seed/water01/400/300',
    originalPrice: 19800,
    groupPrice: 9900,
    currentParticipants: 1,
    targetParticipants: 2,
    deadline: '2026-06-14',
    organizer: '이준호 (물리학과 21)',
    category: '생활용품',
    status: 'active',
  },
  {
    type: 'group-buy',
    title: '로지텍 MX Keys S 키보드 공구 정보',
    description:
      '네이버 공동구매 사이트에서 로지텍 MX Keys S가 11만9천원에 올라왔어요! 정가 15만9천원인데 같이 사면 무료배송까지 됩니다.',
    imageUrl: 'https://picsum.photos/seed/keyboard01/400/300',
    originalPrice: 159000,
    groupPrice: 119000,
    currentParticipants: 7,
    targetParticipants: 10,
    deadline: '2026-06-15',
    organizer: '최서윤 (전산학부 23)',
    category: '전자기기',
    status: 'active',
    externalLink: 'https://example.com/group-buy-keyboard',
  },
  {
    type: 'group-buy',
    title: '닌텐도 프로콘 공구 마감',
    description:
      '해외직구 공동구매로 프로콘 5만2천원에 구매 완료! 다음에 또 열게요.',
    imageUrl: 'https://picsum.photos/seed/nintendo01/400/300',
    originalPrice: 69800,
    groupPrice: 52000,
    currentParticipants: 5,
    targetParticipants: 5,
    deadline: '2026-06-10',
    organizer: '강예진 (전기전자 23)',
    category: '게임',
    status: 'completed',
  },

  // === 배달파티 ===
  {
    type: 'delivery',
    title: '버거킹 같이 주문하실 분',
    description:
      '버거킹 최소배달 15,000원인데 혼자 먹기엔 많아요. 각자 먹고싶은 거 주문하고 배달비 나눠요!',
    imageUrl: 'https://picsum.photos/seed/burger01/400/300',
    minOrderAmount: 15000,
    currentParticipants: 1,
    targetParticipants: 3,
    deadline: '2026-06-08',
    organizer: '박지영 (신소재 23)',
    category: '패스트푸드',
    status: 'active',
    location: '기숙사 A동 로비',
  },
  {
    type: 'delivery',
    title: 'BBQ 치킨 같이 시켜요',
    description:
      'BBQ 배달 최소금액 맞추려고 합니다. 각자 메뉴 골라서 주문해요. 배달비 4000원 나눠요~',
    imageUrl: 'https://picsum.photos/seed/chicken03/400/300',
    minOrderAmount: 18000,
    currentParticipants: 2,
    targetParticipants: 4,
    deadline: '2026-06-08',
    organizer: '정하늘 (기계공학 24)',
    category: '치킨',
    status: 'active',
    location: '기숙사 B동 1층',
  },
  {
    type: 'delivery',
    title: '피자헛 같이 주문해요',
    description:
      '피자헛 2만원 이상 주문해야 배달되는데, 각자 메뉴 골라서 같이 주문합시다! 도서관 앞에서 나눠가져요.',
    imageUrl: 'https://picsum.photos/seed/pizza02/400/300',
    minOrderAmount: 20000,
    currentParticipants: 1,
    targetParticipants: 3,
    deadline: '2026-06-09',
    organizer: '한소영 (생명과학 22)',
    category: '피자',
    status: 'active',
    location: '도서관 앞 벤치',
  },

  // === 택시쉐어 ===
  {
    type: 'taxi-share',
    title: 'GIST → 광주송정역',
    description: '6/10 오후 2시 출발합니다. KTX 타시는 분 같이 가요!',
    imageUrl: 'https://picsum.photos/seed/taxi01/400/300',
    currentParticipants: 2,
    targetParticipants: 4,
    deadline: '2026-06-10',
    organizer: '오태윤 (화학과 22)',
    category: '택시',
    status: 'active',
    location: 'GIST 정문',
    departureTime: '2026-06-10 14:00',
    destination: '광주송정역',
  },
  {
    type: 'taxi-share',
    title: '광주송정역 → GIST',
    description: '6/12 저녁 7시에 송정역 도착 예정이에요. 같이 학교 가실 분!',
    imageUrl: 'https://picsum.photos/seed/taxi02/400/300',
    currentParticipants: 1,
    targetParticipants: 4,
    deadline: '2026-06-12',
    organizer: '김도현 (물리학과 23)',
    category: '택시',
    status: 'active',
    location: '광주송정역 택시승강장',
    departureTime: '2026-06-12 19:00',
    destination: 'GIST',
  },

  // === 카풀 ===
  {
    type: 'carpool',
    title: 'GIST → 상무지구 카풀',
    description:
      '6/11 오후 6시에 출발합니다. 제가 운전해요! 기름값만 나눠주세요.',
    imageUrl: 'https://picsum.photos/seed/carpool01/400/300',
    currentParticipants: 1,
    targetParticipants: 3,
    deadline: '2026-06-11',
    organizer: '윤성호 (기계공학 21)',
    category: '카풀',
    status: 'active',
    location: 'GIST 정문 주차장',
    departureTime: '2026-06-11 18:00',
    destination: '상무지구',
  },
  {
    type: 'carpool',
    title: '주말 광주역 카풀 (왕복)',
    description:
      '토요일 오전 10시 출발, 오후 5시 복귀 예정. 왕복 카풀입니다!',
    imageUrl: 'https://picsum.photos/seed/carpool02/400/300',
    currentParticipants: 0,
    targetParticipants: 3,
    deadline: '2026-06-14',
    organizer: '임수진 (생명과학 22)',
    category: '카풀',
    status: 'active',
    location: 'GIST 기숙사 주차장',
    departureTime: '2026-06-14 10:00',
    destination: '광주역',
  },
];
